//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultilingualApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgWarnings_ar_SA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgWarnings_ar_SA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultilingualApp.MsgWarnings_ar-SA", typeof(MsgWarnings_ar_SA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;كود المنتج&quot; غير موجود!.
        /// </summary>
        internal static string _Code_Product__not_found__ {
            get {
                return ResourceManager.GetString("\'Code Product\' not found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون &quot;منتج الكود&quot; فارغًا!.
        /// </summary>
        internal static string _Code_Product__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Code Product\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون &quot;العميل&quot; فارغًا!.
        /// </summary>
        internal static string _Customer__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Customer\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;عدد المعاملات&quot; غير صالح!.
        /// </summary>
        internal static string _Number_Transactions__is_not_valid__ {
            get {
                return ResourceManager.GetString("\'Number Transactions\' is not valid !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون حقل &quot;عدد المعاملات&quot; فارغًا!.
        /// </summary>
        internal static string _Number_Transactions__should_not_be_empty__ {
            get {
                return ResourceManager.GetString("\'Number Transactions\' should not be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون &quot;وزن الشحن&quot; فارغًا!.
        /// </summary>
        internal static string _Shipping_weight__should_not_be_empty__ {
            get {
                return ResourceManager.GetString("\'Shipping weight\' should not be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون &quot;المورد&quot; فارغًا!.
        /// </summary>
        internal static string _Supplier__Cannot_be_empty__ {
            get {
                return ResourceManager.GetString("\'Supplier\' Cannot be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عدم إفراغ &quot;المورد&quot;!.
        /// </summary>
        internal static string _Supplier__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Supplier\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ. يرجى التحقق من سجل الخطأ للحصول على التفاصيل..
        /// </summary>
        internal static string An_error_occurred__Please_check_the_error_log_for_details_ {
            get {
                return ResourceManager.GetString("An error occurred. Please check the error log for details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد حفظ هذه البيانات ؟؟؟.
        /// </summary>
        internal static string Are_you_sure_you_want_to_save_this_data____ {
            get {
                return ResourceManager.GetString("Are you sure you want to save this data ???", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال منتج واحد على الأقل!.
        /// </summary>
        internal static string At_least_1_product_must_be_input_ {
            get {
                return ResourceManager.GetString("At least 1 product must be input!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع تخزين ملفات النسخ الاحتياطي لم يتم تحديده بعد!.
        /// </summary>
        internal static string Backup_file_storage_location_Not_yet_selected__ {
            get {
                return ResourceManager.GetString("Backup file storage location Not yet selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج كود.
        /// </summary>
        internal static string code_product {
            get {
                return ResourceManager.GetString("code product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتصال بشاشة العميل ، يرجى محاولة منفذ آخر..
        /// </summary>
        internal static string Connection_to_customer_display__please_try_another_port_ {
            get {
                return ResourceManager.GetString("Connection to customer display, please try another port.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيؤدي استمرار هذا إلى تسجيل خروجك وستفقد أية تغييرات غير محفوظة. احفظ التغييرات قبل المتابعة. هل أنت متأكد أنك تريد الاستمرار؟.
        /// </summary>
        internal static string Continuing_this_will_log_you_out_and_any_unsaved_changes_will_be_lost__Save_your_changes_before_proceeding__Are_you_sure_you_want_to_continue_ {
            get {
                return ResourceManager.GetString("Continuing this will log you out and any unsaved changes will be lost. Save your " +
                        "changes before proceeding. Are you sure you want to continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على مدينة البيانات / أصل الوصاية.
        /// </summary>
        internal static string Data_city_regency_origin_not_found {
            get {
                return ResourceManager.GetString("Data city/regency origin not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال فاتورة البيانات بالفعل.
        /// </summary>
        internal static string Data_invoice_already_entered {
            get {
                return ResourceManager.GetString("Data invoice already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيع فاتورة البيانات غير موجود.
        /// </summary>
        internal static string Data_invoice_sale_not_found {
            get {
                return ResourceManager.GetString("Data invoice sale not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال دفع البيانات بالفعل.
        /// </summary>
        internal static string Data_payment_already_entered {
            get {
                return ResourceManager.GetString("Data payment already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال منتج البيانات بالفعل.
        /// </summary>
        internal static string Data_product_already_entered {
            get {
                return ResourceManager.GetString("Data product already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتج البيانات غير موجود.
        /// </summary>
        internal static string Data_product_not_found {
            get {
                return ResourceManager.GetString("Data product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة شراء البيانات غير موجودة.
        /// </summary>
        internal static string Data_purchase_invoice_not_found {
            get {
                return ResourceManager.GetString("Data purchase invoice not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد مبيعات البيانات غير موجود.
        /// </summary>
        internal static string Data_sales_Credit_not_found {
            get {
                return ResourceManager.GetString("Data sales Credit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على مورد البيانات.
        /// </summary>
        internal static string Data_supplier_not_found {
            get {
                return ResourceManager.GetString("Data supplier not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال مصاريف نوع البيانات بالفعل.
        /// </summary>
        internal static string Data_type_expense_already_entered {
            get {
                return ResourceManager.GetString("Data type expense already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على مصاريف نوع البيانات.
        /// </summary>
        internal static string Data_type_expense_not_found {
            get {
                return ResourceManager.GetString("Data type expense not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد استمرار العملية؟.
        /// </summary>
        internal static string Do_you_want_the_process_to_continue__ {
            get {
                return ResourceManager.GetString("Do you want the process to continue ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد متابعة عملية الطباعة؟.
        /// </summary>
        internal static string Do_you_want_to_continue_the_printing_process_ {
            get {
                return ResourceManager.GetString("Do you want to continue the printing process?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد متابعة عملية الطباعة؟.
        /// </summary>
        internal static string Do_you_want_to_continue_the_printing_process__ {
            get {
                return ResourceManager.GetString("Do you want to continue the printing process ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد متابعة عملية النسخ الاحتياطي لقاعدة البيانات؟.
        /// </summary>
        internal static string Do_you_want_to_continue_with_the_database_backup_process_ {
            get {
                return ResourceManager.GetString("Do you want to continue with the database backup process?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف هذه البيانات؟.
        /// </summary>
        internal static string Do_you_want_to_delete_this_data_ {
            get {
                return ResourceManager.GetString("Do you want to delete this data?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف لم يتم اختياره بعد.
        /// </summary>
        internal static string Employee_Not_yet_selected {
            get {
                return ResourceManager.GetString("Employee Not yet selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع ملف Excel واسمه لم يتم تحديدهما بعد..
        /// </summary>
        internal static string Excel_file_location_and_name_not_yet_selected_ {
            get {
                return ResourceManager.GetString("Excel file location and name not yet selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف النسخ الاحتياطي لم يتم تحديده بعد!.
        /// </summary>
        internal static string File_backup_Not_yet_selected__ {
            get {
                return ResourceManager.GetString("File backup Not yet selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور غير صحيحة !!!.
        /// </summary>
        internal static string Incorrect_user_name_or_password____ {
            get {
                return ResourceManager.GetString("Incorrect user name or password !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومة.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الضريبة غير صالح..
        /// </summary>
        internal static string Invalid_Tax_ID_ {
            get {
                return ResourceManager.GetString("Invalid Tax ID.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التحقق من التحديث الأخير..
        /// </summary>
        internal static string Latest_update_check_process_has_failed_ {
            get {
                return ResourceManager.GetString("Latest update check process has failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasi dan name file Excel Not yet selected..
        /// </summary>
        internal static string Lokasi_dan_name_file_Excel_Not_yet_selected_ {
            get {
                return ResourceManager.GetString("Lokasi dan name file Excel Not yet selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد فئة واحدة كحد أدنى.
        /// </summary>
        internal static string Minimum_1_category_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 category must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد عميل واحد على الأقل.
        /// </summary>
        internal static string Minimum_1_customer_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 customer must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار موظف واحد كحد أدنى.
        /// </summary>
        internal static string Minimum_1_employee_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 employee must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال فاتورة واحدة على الأقل!.
        /// </summary>
        internal static string Minimum_1_invoice_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 invoice must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال مصاريف عنصر واحد على الأقل!.
        /// </summary>
        internal static string Minimum_1_item_expense_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 item expense must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال منتج واحد على الأقل!.
        /// </summary>
        internal static string Minimum_1_item_product_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 item product must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال عنصر منتج واحد على الأقل!.
        /// </summary>
        internal static string Minimum_1_product_item_must_be_inputted__ {
            get {
                return ResourceManager.GetString("Minimum 1 product item must be inputted !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال منتج واحد على الأقل!.
        /// </summary>
        internal static string Minimum_1_product_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 product must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد سبب واحد على الأقل.
        /// </summary>
        internal static string Minimum_1_reason_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 reason must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد مورد واحد على الأقل.
        /// </summary>
        internal static string Minimum_1_supplier_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 supplier must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد الحد الأدنى من مصروفات النوع 1.
        /// </summary>
        internal static string Minimum_1_type_expense_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 type expense must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد منتج اسم واحد على الأقل!.
        /// </summary>
        internal static string Minimum_one_name_product_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one name product must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد الرمز الشريطي لتسمية الموضع الواحد على الأقل!.
        /// </summary>
        internal static string Minimum_one_position_label_barcode_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one position label barcode must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد الحد الأدنى لسعر تسمية المركز الواحد!.
        /// </summary>
        internal static string Minimum_one_position_label_price_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one position label price must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إدخال اسم العميل بعد.
        /// </summary>
        internal static string Name_Customer_Not_yet_entered {
            get {
                return ResourceManager.GetString("Name Customer Not yet entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج غير مسموح به فارغًا.
        /// </summary>
        internal static string Name_product_not_allowed_empty {
            get {
                return ResourceManager.GetString("Name product not allowed empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المورد لم يتم إدخاله بعد.
        /// </summary>
        internal static string Name_supplier_Not_yet_entered {
            get {
                return ResourceManager.GetString("Name supplier Not yet entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس هناك دفع تاريخ المعلومات.
        /// </summary>
        internal static string Not_yet_there_Information_history_payment {
            get {
                return ResourceManager.GetString("Not yet there Information history payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون كلمة المرور وكلمة المرور متطابقتين.
        /// </summary>
        internal static string Password_and_confirmation_password_must_be_the_same {
            get {
                return ResourceManager.GetString("Password and confirmation password must be the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادفع نقدا.
        /// </summary>
        internal static string Pay_Cash {
            get {
                return ResourceManager.GetString("Pay Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع عن طريق البطاقة.
        /// </summary>
        internal static string Pay_via_Card {
            get {
                return ResourceManager.GetString("Pay via Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تحديد عميل.
        /// </summary>
        internal static string Please_select_a_customer {
            get {
                return ResourceManager.GetString("Please select a customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على بيانات المنتج.
        /// </summary>
        internal static string Product_data_not_found {
            get {
                return ResourceManager.GetString("Product data not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يكون اسم المنتج فارغًا.
        /// </summary>
        internal static string Product_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("Product name cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على بيانات ائتمان الشراء.
        /// </summary>
        internal static string Purchase_Credit_data_not_found {
            get {
                return ResourceManager.GetString("Purchase Credit data not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية تدفع أقل!.
        /// </summary>
        internal static string quantity_pay_less__ {
            get {
                return ResourceManager.GetString("quantity pay less !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، لم يتم العثور على تقرير بيانات الشراء.
        /// </summary>
        internal static string Sorry__Purchase_data_report_was_not_found {
            get {
                return ResourceManager.GetString("Sorry, Purchase data report was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، المبلغ المدفوع يتجاوز الرصيد المتبقي.
        /// </summary>
        internal static string Sorry__quantity_payment_exceeds__remaining_credit {
            get {
                return ResourceManager.GetString("Sorry, quantity payment exceeds  remaining credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، دفع الكمية يتجاوز الديون المتبقية.
        /// </summary>
        internal static string Sorry__quantity_payment_exceeds__remaining_debt {
            get {
                return ResourceManager.GetString("Sorry, quantity payment exceeds  remaining debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، يجب ألا يتجاوز إرجاع الكمية بيع الكمية.
        /// </summary>
        internal static string Sorry__quantity_return_should_not_exceeds__quantity_sale {
            get {
                return ResourceManager.GetString("Sorry, quantity return should not exceeds  quantity sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، لم يتم العثور على ملف العميل الرئيسي..
        /// </summary>
        internal static string Sorry__the_Customer_master_file_was_not_found_ {
            get {
                return ResourceManager.GetString("Sorry, the Customer master file was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، لم يتم العثور على تقرير شراء ديون بطاقة البيانات.
        /// </summary>
        internal static string Sorry__the_data_card_debt_purchase_report_was_not_found {
            get {
                return ResourceManager.GetString("Sorry, the data card debt purchase report was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، إدخال البيانات غير مكتمل!.
        /// </summary>
        internal static string Sorry__the_data_entry_is_incomplete_ {
            get {
                return ResourceManager.GetString("Sorry, the data entry is incomplete!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، البيانات التي أدخلتها فشلت في الحفظ! حاول مرة اخرى..
        /// </summary>
        internal static string Sorry__the_data_you_entered_failed_to_save__Please_try_again_ {
            get {
                return ResourceManager.GetString("Sorry, the data you entered failed to save! Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، النطاق الزمني خاطئ !!!.
        /// </summary>
        internal static string Sorry__the_date_range_is_wrong____ {
            get {
                return ResourceManager.GetString("Sorry, the date range is wrong !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، لم يتم تعيين رابط / عنوان URL الخاص بالتحديث عبر الإنترنت حتى الآن !!!.
        /// </summary>
        internal static string Sorry__the_Online_Update_link_URL_has_not_been_set_yet___ {
            get {
                return ResourceManager.GetString("Sorry, the Online Update link/URL has not been set yet!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، لم يتم تعيين رابط / URL التحديث عبر الإنترنت حتى الآن !!! \ n فشلت عملية التحقق من التحديث الأخير..
        /// </summary>
        internal static string Sorry__the_Online_Update_link_URL_has_not_been_set_yet____nLatest_update_check_process_has_failed_ {
            get {
                return ResourceManager.GetString("Sorry, the Online Update link/URL has not been set yet!!!\\nLatest update check pr" +
                        "ocess has failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، لا يمكن أن تتجاوز الكمية المعادة الكمية المباعة.
        /// </summary>
        internal static string Sorry__the_quantity_returned_cannot_exceed_the_quantity_sold {
            get {
                return ResourceManager.GetString("Sorry, the quantity returned cannot exceed the quantity sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، ليس لديك الصلاحية للوصول إلى هذه القائمة.
        /// </summary>
        internal static string Sorry__you_do_not_have_the_authority_to_access_this_menu {
            get {
                return ResourceManager.GetString("Sorry, you do not have the authority to access this menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذراً لم يتم تعيين طابع الملك API الخاص بالبريد !!! \ n لا يمكن متابعة عملية التحقق من تكلفة الشحن..
        /// </summary>
        internal static string Sorry_API_king_postage_Not_yet_set_____nCost_shipping_check_process_cannot_be_continued_ {
            get {
                return ResourceManager.GetString("Sorry API king postage Not yet set !!!\\nCost shipping check process cannot be con" +
                        "tinued.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا البيانات &quot;الفئة&quot; لم يتم تحديدها بعد..
        /// </summary>
        internal static string Sorry_data__Category__has_not_been_selected_yet_ {
            get {
                return ResourceManager.GetString("Sorry data \'Category\' has not been selected yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا البيانات &quot;الفئة&quot; لم يتم تحديدها بعد..
        /// </summary>
        internal static string Sorry_data__Category__Not_yet_selected_ {
            get {
                return ResourceManager.GetString("Sorry data \'Category\' Not yet selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا فشل حذف البيانات!.
        /// </summary>
        internal static string Sorry_data_failed_to_delete__ {
            get {
                return ResourceManager.GetString("Sorry data failed to delete !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا دفع قسم الدفع نقدا الشراء لا يمكن حذفها.
        /// </summary>
        internal static string Sorry_Dept_Payment_Purchase_cash_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry Dept Payment Purchase cash can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ملف سيد الفئة غير موجود..
        /// </summary>
        internal static string Sorry_file_master_Category_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Category not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ملف سيد دروبشيبر غير موجود..
        /// </summary>
        internal static string Sorry_file_master_Dropshipper_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Dropshipper not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ملف سيد المنتج غير موجود..
        /// </summary>
        internal static string Sorry_file_master_Product_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Product not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ملف سيد المورد غير موجود..
        /// </summary>
        internal static string Sorry_file_master_Supplier_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Supplier not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ملف سيد الضريبة غير موجود..
        /// </summary>
        internal static string Sorry_file_master_Tax_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Tax not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لا يمكن حذف الدفع النقدي للمبيعات الائتمانية.
        /// </summary>
        internal static string Sorry_payment_credit_sales_cash_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry payment credit sales cash can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسف كمية تدفع أقل.
        /// </summary>
        internal static string Sorry_quantity_pay_less {
            get {
                return ResourceManager.GetString("Sorry quantity pay less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير بطاقة البيانات الأسهم غير موجود.
        /// </summary>
        internal static string Sorry_report_data_card_stock_not_found {
            get {
                return ResourceManager.GetString("Sorry report data card stock not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات بطاقة الائتمان البيانات غير موجود.
        /// </summary>
        internal static string Sorry_report_data_Credit_Card_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data Credit Card sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات بيانات الائتمان غير موجود.
        /// </summary>
        internal static string Sorry_report_data_credit_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data credit sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير بيانات العميل المنتج غير موجود.
        /// </summary>
        internal static string Sorry_report_data_customer_product_not_found {
            get {
                return ResourceManager.GetString("Sorry report data customer product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، تقرير بيانات قسم الدفع شراء غير موجود.
        /// </summary>
        internal static string Sorry_report_data_Dept_Payment_Purchase_not_found {
            get {
                return ResourceManager.GetString("Sorry report data Dept Payment Purchase not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، تقرير حساب بيانات التكلفة غير موجود.
        /// </summary>
        internal static string Sorry_report_data_expense_cost_not_found {
            get {
                return ResourceManager.GetString("Sorry report data expense cost not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً ، لم يتم العثور على بيانات تقرير الدخل والمصروفات &quot;.
        /// </summary>
        internal static string Sorry_report_data_Income_and_Expense_not_found_ {
            get {
                return ResourceManager.GetString("Sorry report data Income and Expense not found\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير بيانات القرض غير موجود.
        /// </summary>
        internal static string Sorry_report_data_loan_not_found {
            get {
                return ResourceManager.GetString("Sorry report data loan not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير فقدان البيانات الربح غير موجود.
        /// </summary>
        internal static string Sorry_report_data_loss_profit_not_found {
            get {
                return ResourceManager.GetString("Sorry report data loss profit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات الائتمان دفع البيانات غير موجود.
        /// </summary>
        internal static string Sorry_report_data_payment_credit_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data payment credit sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات عودة البيانات غير موجود.
        /// </summary>
        internal static string Sorry_report_data_return_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data return sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير الموظف بيانات الراتب غير موجود.
        /// </summary>
        internal static string Sorry_report_data_salary_employee_not_found {
            get {
                return ResourceManager.GetString("Sorry report data salary employee not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات البيانات غير موجود.
        /// </summary>
        internal static string Sorry_report_data_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير مبيعات البيانات لكل كاشير غير موجود.
        /// </summary>
        internal static string Sorry_report_data_sales_per_Cashier_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales per Cashier not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير بيانات مبيعات المنتج المفضل غير موجود.
        /// </summary>
        internal static string Sorry_report_data_sales_product_favorit_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales product favorit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا تقرير بيانات المخزون المنتج غير موجود.
        /// </summary>
        internal static string Sorry_report_data_stock_product_not_found {
            get {
                return ResourceManager.GetString("Sorry report data stock product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات تقرير آسف لم يتم العثور على تعديل المخزون.
        /// </summary>
        internal static string Sorry_report_dataStock_Adjustment_not_found {
            get {
                return ResourceManager.GetString("Sorry report dataStock Adjustment not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسف حق الوصول &quot;المسؤول&quot; لا يمكن حذفه.
        /// </summary>
        internal static string Sorry_Right_Access__Administrator__can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry Right Access \'Administrator\' can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسف حق الوصول &quot;المسؤول&quot; لا يمكن تحريرها.
        /// </summary>
        internal static string Sorry_Right_Access__Administrator__cannot_be_edited {
            get {
                return ResourceManager.GetString("Sorry Right Access \'Administrator\' cannot be edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آسف لم يتم العثور على البيانات التي وجدت.
        /// </summary>
        internal static string Sorry_the_data_you_found_was_not_found {
            get {
                return ResourceManager.GetString("Sorry the data you found was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة غير متوفرة حاليا:.
        /// </summary>
        internal static string The_page_is_currently_unavailable_ {
            get {
                return ResourceManager.GetString("The page is currently unavailable:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم استخدام هذه البيانات بالفعل في عملية أخرى..
        /// </summary>
        internal static string This_data_is_already_being_used_for_another_process_ {
            get {
                return ResourceManager.GetString("This data is already being used for another process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تكمل إدخال بيانات المنتج!.
        /// </summary>
        internal static string You_have_not_completed_the_input_of_product_data__ {
            get {
                return ResourceManager.GetString("You have not completed the input of product data !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تكمل إدخال بيانات الدفع!.
        /// </summary>
        internal static string You_have_not_completed_the_payment_data_input__ {
            get {
                return ResourceManager.GetString("You have not completed the payment data input !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تكمل إدخال بيانات المنتج حتى الآن!.
        /// </summary>
        internal static string You_haven_t_completed_the_product_data_input_yet_ {
            get {
                return ResourceManager.GetString("You haven\'t completed the product data input yet!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت الفترة التجريبية الخاصة بك. يرجى شراء ترخيص لمواصلة استخدام التطبيق..
        /// </summary>
        internal static string Your_trial_has_expired__Please_purchase_a_license_to_continue_using_the_application_ {
            get {
                return ResourceManager.GetString("Your trial has expired. Please purchase a license to continue using the applicati" +
                        "on.", resourceCulture);
            }
        }
    }
}
