//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultilingualApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgWarnings_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgWarnings_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultilingualApp.MsgWarnings_en-US", typeof(MsgWarnings_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;City/Regency Origin&apos; should not empty !.
        /// </summary>
        internal static string _City_Regency_Origin__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'City/Regency Origin\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Code Product&apos; not found !.
        /// </summary>
        internal static string _Code_Product__not_found__ {
            get {
                return ResourceManager.GetString("\'Code Product\' not found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Code Product&apos; should not empty !.
        /// </summary>
        internal static string _Code_Product__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Code Product\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Customer&apos; should not empty !.
        /// </summary>
        internal static string _Customer__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Customer\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Number Transactions&apos; is not valid !.
        /// </summary>
        internal static string _Number_Transactions__is_not_valid__ {
            get {
                return ResourceManager.GetString("\'Number Transactions\' is not valid !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Number Transactions&apos; should not be empty !.
        /// </summary>
        internal static string _Number_Transactions__should_not_be_empty__ {
            get {
                return ResourceManager.GetString("\'Number Transactions\' should not be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Shipping weight&apos; should not be empty !.
        /// </summary>
        internal static string _Shipping_weight__should_not_be_empty__ {
            get {
                return ResourceManager.GetString("\'Shipping weight\' should not be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Supplier&apos; Cannot be empty !.
        /// </summary>
        internal static string _Supplier__Cannot_be_empty__ {
            get {
                return ResourceManager.GetString("\'Supplier\' Cannot be empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Supplier&apos; should not empty !.
        /// </summary>
        internal static string _Supplier__should_not_empty__ {
            get {
                return ResourceManager.GetString("\'Supplier\' should not empty !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please check the error log for details..
        /// </summary>
        internal static string An_error_occurred__Please_check_the_error_log_for_details_ {
            get {
                return ResourceManager.GetString("An error occurred. Please check the error log for details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this data ???.
        /// </summary>
        internal static string Are_you_sure_you_want_to_save_this_data____ {
            get {
                return ResourceManager.GetString("Are you sure you want to save this data ???", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 product must be input!.
        /// </summary>
        internal static string At_least_1_product_must_be_input_ {
            get {
                return ResourceManager.GetString("At least 1 product must be input!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file storage location Not yet selected !.
        /// </summary>
        internal static string Backup_file_storage_location_Not_yet_selected__ {
            get {
                return ResourceManager.GetString("Backup file storage location Not yet selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code product.
        /// </summary>
        internal static string code_product {
            get {
                return ResourceManager.GetString("code product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to customer display, please try another port..
        /// </summary>
        internal static string Connection_to_customer_display__please_try_another_port_ {
            get {
                return ResourceManager.GetString("Connection to customer display, please try another port.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing this will log you out and any unsaved changes will be lost. Save your changes before proceeding. Are you sure you want to continue?.
        /// </summary>
        internal static string Continuing_this_will_log_you_out_and_any_unsaved_changes_will_be_lost__Save_your_changes_before_proceeding__Are_you_sure_you_want_to_continue_ {
            get {
                return ResourceManager.GetString("Continuing this will log you out and any unsaved changes will be lost. Save your " +
                        "changes before proceeding. Are you sure you want to continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data city/regency origin not found.
        /// </summary>
        internal static string Data_city_regency_origin_not_found {
            get {
                return ResourceManager.GetString("Data city/regency origin not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data invoice already entered.
        /// </summary>
        internal static string Data_invoice_already_entered {
            get {
                return ResourceManager.GetString("Data invoice already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data invoice sale not found.
        /// </summary>
        internal static string Data_invoice_sale_not_found {
            get {
                return ResourceManager.GetString("Data invoice sale not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data payment already entered.
        /// </summary>
        internal static string Data_payment_already_entered {
            get {
                return ResourceManager.GetString("Data payment already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data product already entered.
        /// </summary>
        internal static string Data_product_already_entered {
            get {
                return ResourceManager.GetString("Data product already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data product not found.
        /// </summary>
        internal static string Data_product_not_found {
            get {
                return ResourceManager.GetString("Data product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data purchase invoice not found.
        /// </summary>
        internal static string Data_purchase_invoice_not_found {
            get {
                return ResourceManager.GetString("Data purchase invoice not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sales Credit not found.
        /// </summary>
        internal static string Data_sales_Credit_not_found {
            get {
                return ResourceManager.GetString("Data sales Credit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data supplier not found.
        /// </summary>
        internal static string Data_supplier_not_found {
            get {
                return ResourceManager.GetString("Data supplier not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type expense already entered.
        /// </summary>
        internal static string Data_type_expense_already_entered {
            get {
                return ResourceManager.GetString("Data type expense already entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type expense not found.
        /// </summary>
        internal static string Data_type_expense_not_found {
            get {
                return ResourceManager.GetString("Data type expense not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want the process to continue ?.
        /// </summary>
        internal static string Do_you_want_the_process_to_continue__ {
            get {
                return ResourceManager.GetString("Do you want the process to continue ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue the printing process?.
        /// </summary>
        internal static string Do_you_want_to_continue_the_printing_process_ {
            get {
                return ResourceManager.GetString("Do you want to continue the printing process?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue the printing process ?.
        /// </summary>
        internal static string Do_you_want_to_continue_the_printing_process__ {
            get {
                return ResourceManager.GetString("Do you want to continue the printing process ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue with the database backup process?.
        /// </summary>
        internal static string Do_you_want_to_continue_with_the_database_backup_process_ {
            get {
                return ResourceManager.GetString("Do you want to continue with the database backup process?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this data?.
        /// </summary>
        internal static string Do_you_want_to_delete_this_data_ {
            get {
                return ResourceManager.GetString("Do you want to delete this data?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Not yet selected.
        /// </summary>
        internal static string Employee_Not_yet_selected {
            get {
                return ResourceManager.GetString("Employee Not yet selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file location and name not yet selected..
        /// </summary>
        internal static string Excel_file_location_and_name_not_yet_selected_ {
            get {
                return ResourceManager.GetString("Excel file location and name not yet selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File backup Not yet selected !.
        /// </summary>
        internal static string File_backup_Not_yet_selected__ {
            get {
                return ResourceManager.GetString("File backup Not yet selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password !!!.
        /// </summary>
        internal static string Incorrect_user_name_or_password____ {
            get {
                return ResourceManager.GetString("Incorrect user name or password !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tax ID..
        /// </summary>
        internal static string Invalid_Tax_ID_ {
            get {
                return ResourceManager.GetString("Invalid Tax ID.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest update check process has failed..
        /// </summary>
        internal static string Latest_update_check_process_has_failed_ {
            get {
                return ResourceManager.GetString("Latest update check process has failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasi dan name file Excel Not yet selected..
        /// </summary>
        internal static string Lokasi_dan_name_file_Excel_Not_yet_selected_ {
            get {
                return ResourceManager.GetString("Lokasi dan name file Excel Not yet selected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 category must selected.
        /// </summary>
        internal static string Minimum_1_category_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 category must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 customer must selected.
        /// </summary>
        internal static string Minimum_1_customer_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 customer must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 employee must selected.
        /// </summary>
        internal static string Minimum_1_employee_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 employee must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 invoice must entered !.
        /// </summary>
        internal static string Minimum_1_invoice_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 invoice must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 item expense must entered !.
        /// </summary>
        internal static string Minimum_1_item_expense_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 item expense must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 item product must entered !.
        /// </summary>
        internal static string Minimum_1_item_product_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 item product must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 product item must be inputted !.
        /// </summary>
        internal static string Minimum_1_product_item_must_be_inputted__ {
            get {
                return ResourceManager.GetString("Minimum 1 product item must be inputted !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 product must entered !.
        /// </summary>
        internal static string Minimum_1_product_must_entered__ {
            get {
                return ResourceManager.GetString("Minimum 1 product must entered !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 reason must selected.
        /// </summary>
        internal static string Minimum_1_reason_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 reason must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 supplier must selected.
        /// </summary>
        internal static string Minimum_1_supplier_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 supplier must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 type expense must selected.
        /// </summary>
        internal static string Minimum_1_type_expense_must_selected {
            get {
                return ResourceManager.GetString("Minimum 1 type expense must selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum one name product must selected !.
        /// </summary>
        internal static string Minimum_one_name_product_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one name product must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum one position label barcode must selected !.
        /// </summary>
        internal static string Minimum_one_position_label_barcode_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one position label barcode must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum one position label price must selected !.
        /// </summary>
        internal static string Minimum_one_position_label_price_must_selected__ {
            get {
                return ResourceManager.GetString("Minimum one position label price must selected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Customer Not yet entered.
        /// </summary>
        internal static string Name_Customer_Not_yet_entered {
            get {
                return ResourceManager.GetString("Name Customer Not yet entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name product not allowed empty.
        /// </summary>
        internal static string Name_product_not_allowed_empty {
            get {
                return ResourceManager.GetString("Name product not allowed empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name supplier Not yet entered.
        /// </summary>
        internal static string Name_supplier_Not_yet_entered {
            get {
                return ResourceManager.GetString("Name supplier Not yet entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet there Information history payment.
        /// </summary>
        internal static string Not_yet_there_Information_history_payment {
            get {
                return ResourceManager.GetString("Not yet there Information history payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password must be the same.
        /// </summary>
        internal static string Password_and_confirmation_password_must_be_the_same {
            get {
                return ResourceManager.GetString("Password and confirmation password must be the same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Cash.
        /// </summary>
        internal static string Pay_Cash {
            get {
                return ResourceManager.GetString("Pay Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via Card.
        /// </summary>
        internal static string Pay_via_Card {
            get {
                return ResourceManager.GetString("Pay via Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer.
        /// </summary>
        internal static string Please_select_a_customer {
            get {
                return ResourceManager.GetString("Please select a customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product data not found.
        /// </summary>
        internal static string Product_data_not_found {
            get {
                return ResourceManager.GetString("Product data not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name cannot be empty.
        /// </summary>
        internal static string Product_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("Product name cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Credit data not found.
        /// </summary>
        internal static string Purchase_Credit_data_not_found {
            get {
                return ResourceManager.GetString("Purchase Credit data not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity pay less !.
        /// </summary>
        internal static string quantity_pay_less__ {
            get {
                return ResourceManager.GetString("quantity pay less !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Purchase data report was not found.
        /// </summary>
        internal static string Sorry__Purchase_data_report_was_not_found {
            get {
                return ResourceManager.GetString("Sorry, Purchase data report was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, quantity payment exceeds  remaining credit.
        /// </summary>
        internal static string Sorry__quantity_payment_exceeds__remaining_credit {
            get {
                return ResourceManager.GetString("Sorry, quantity payment exceeds  remaining credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, quantity payment exceeds  remaining debt.
        /// </summary>
        internal static string Sorry__quantity_payment_exceeds__remaining_debt {
            get {
                return ResourceManager.GetString("Sorry, quantity payment exceeds  remaining debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, quantity return should not exceeds  quantity sale.
        /// </summary>
        internal static string Sorry__quantity_return_should_not_exceeds__quantity_sale {
            get {
                return ResourceManager.GetString("Sorry, quantity return should not exceeds  quantity sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Customer master file was not found..
        /// </summary>
        internal static string Sorry__the_Customer_master_file_was_not_found_ {
            get {
                return ResourceManager.GetString("Sorry, the Customer master file was not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the data card debt purchase report was not found.
        /// </summary>
        internal static string Sorry__the_data_card_debt_purchase_report_was_not_found {
            get {
                return ResourceManager.GetString("Sorry, the data card debt purchase report was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the data entry is incomplete!.
        /// </summary>
        internal static string Sorry__the_data_entry_is_incomplete_ {
            get {
                return ResourceManager.GetString("Sorry, the data entry is incomplete!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the data you entered failed to save! Please try again..
        /// </summary>
        internal static string Sorry__the_data_you_entered_failed_to_save__Please_try_again_ {
            get {
                return ResourceManager.GetString("Sorry, the data you entered failed to save! Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the date range is wrong !!!.
        /// </summary>
        internal static string Sorry__the_date_range_is_wrong____ {
            get {
                return ResourceManager.GetString("Sorry, the date range is wrong !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Online Update link/URL has not been set yet!!!.
        /// </summary>
        internal static string Sorry__the_Online_Update_link_URL_has_not_been_set_yet___ {
            get {
                return ResourceManager.GetString("Sorry, the Online Update link/URL has not been set yet!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the Online Update link/URL has not been set yet!!!\nLatest update check process has failed..
        /// </summary>
        internal static string Sorry__the_Online_Update_link_URL_has_not_been_set_yet____nLatest_update_check_process_has_failed_ {
            get {
                return ResourceManager.GetString("Sorry, the Online Update link/URL has not been set yet!!!\\nLatest update check pr" +
                        "ocess has failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the quantity returned cannot exceed the quantity sold.
        /// </summary>
        internal static string Sorry__the_quantity_returned_cannot_exceed_the_quantity_sold {
            get {
                return ResourceManager.GetString("Sorry, the quantity returned cannot exceed the quantity sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have the authority to access this menu.
        /// </summary>
        internal static string Sorry__you_do_not_have_the_authority_to_access_this_menu {
            get {
                return ResourceManager.GetString("Sorry, you do not have the authority to access this menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry API king postage Not yet set !!!\nCost shipping check process cannot be continued..
        /// </summary>
        internal static string Sorry_API_king_postage_Not_yet_set_____nCost_shipping_check_process_cannot_be_continued_ {
            get {
                return ResourceManager.GetString("Sorry API king postage Not yet set !!!\\nCost shipping check process cannot be con" +
                        "tinued.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry data &apos;Category&apos; has not been selected yet..
        /// </summary>
        internal static string Sorry_data__Category__has_not_been_selected_yet_ {
            get {
                return ResourceManager.GetString("Sorry data \'Category\' has not been selected yet.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry data &apos;Category&apos; has not been selected yet..
        /// </summary>
        internal static string Sorry_data__Category__has_not_been_selected_yet_1 {
            get {
                return ResourceManager.GetString("Sorry data \'Category\' has not been selected yet.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry data failed to delete !.
        /// </summary>
        internal static string Sorry_data_failed_to_delete__ {
            get {
                return ResourceManager.GetString("Sorry data failed to delete !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Dept Payment Purchase cash can not be deleted.
        /// </summary>
        internal static string Sorry_Dept_Payment_Purchase_cash_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry Dept Payment Purchase cash can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry file master Category not found..
        /// </summary>
        internal static string Sorry_file_master_Category_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Category not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry file master Dropshipper not found..
        /// </summary>
        internal static string Sorry_file_master_Dropshipper_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Dropshipper not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry file master Product not found..
        /// </summary>
        internal static string Sorry_file_master_Product_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Product not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry file master Supplier not found..
        /// </summary>
        internal static string Sorry_file_master_Supplier_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Supplier not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry file master Tax not found..
        /// </summary>
        internal static string Sorry_file_master_Tax_not_found_ {
            get {
                return ResourceManager.GetString("Sorry file master Tax not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry payment credit sales cash can not be deleted.
        /// </summary>
        internal static string Sorry_payment_credit_sales_cash_can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry payment credit sales cash can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry quantity pay less.
        /// </summary>
        internal static string Sorry_quantity_pay_less {
            get {
                return ResourceManager.GetString("Sorry quantity pay less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data card stock not found.
        /// </summary>
        internal static string Sorry_report_data_card_stock_not_found {
            get {
                return ResourceManager.GetString("Sorry report data card stock not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data Credit Card sales not found.
        /// </summary>
        internal static string Sorry_report_data_Credit_Card_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data Credit Card sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data credit sales not found.
        /// </summary>
        internal static string Sorry_report_data_credit_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data credit sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data customer product not found.
        /// </summary>
        internal static string Sorry_report_data_customer_product_not_found {
            get {
                return ResourceManager.GetString("Sorry report data customer product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data Dept Payment Purchase not found.
        /// </summary>
        internal static string Sorry_report_data_Dept_Payment_Purchase_not_found {
            get {
                return ResourceManager.GetString("Sorry report data Dept Payment Purchase not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data expense cost not found.
        /// </summary>
        internal static string Sorry_report_data_expense_cost_not_found {
            get {
                return ResourceManager.GetString("Sorry report data expense cost not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data Income and Expense not found&quot;.
        /// </summary>
        internal static string Sorry_report_data_Income_and_Expense_not_found_ {
            get {
                return ResourceManager.GetString("Sorry report data Income and Expense not found\"", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data loan not found.
        /// </summary>
        internal static string Sorry_report_data_loan_not_found {
            get {
                return ResourceManager.GetString("Sorry report data loan not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data loss profit not found.
        /// </summary>
        internal static string Sorry_report_data_loss_profit_not_found {
            get {
                return ResourceManager.GetString("Sorry report data loss profit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data payment credit sales not found.
        /// </summary>
        internal static string Sorry_report_data_payment_credit_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data payment credit sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data return sales not found.
        /// </summary>
        internal static string Sorry_report_data_return_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data return sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data salary employee not found.
        /// </summary>
        internal static string Sorry_report_data_salary_employee_not_found {
            get {
                return ResourceManager.GetString("Sorry report data salary employee not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data sales not found.
        /// </summary>
        internal static string Sorry_report_data_sales_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data sales per Cashier not found.
        /// </summary>
        internal static string Sorry_report_data_sales_per_Cashier_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales per Cashier not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data sales product favorit not found.
        /// </summary>
        internal static string Sorry_report_data_sales_product_favorit_not_found {
            get {
                return ResourceManager.GetString("Sorry report data sales product favorit not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report data stock product not found.
        /// </summary>
        internal static string Sorry_report_data_stock_product_not_found {
            get {
                return ResourceManager.GetString("Sorry report data stock product not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry report dataStock Adjustment not found.
        /// </summary>
        internal static string Sorry_report_dataStock_Adjustment_not_found {
            get {
                return ResourceManager.GetString("Sorry report dataStock Adjustment not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Right Access &apos;Administrator&apos; can not be deleted.
        /// </summary>
        internal static string Sorry_Right_Access__Administrator__can_not_be_deleted {
            get {
                return ResourceManager.GetString("Sorry Right Access \'Administrator\' can not be deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Right Access &apos;Administrator&apos; cannot be edited.
        /// </summary>
        internal static string Sorry_Right_Access__Administrator__cannot_be_edited {
            get {
                return ResourceManager.GetString("Sorry Right Access \'Administrator\' cannot be edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry the data you found was not found.
        /// </summary>
        internal static string Sorry_the_data_you_found_was_not_found {
            get {
                return ResourceManager.GetString("Sorry the data you found was not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page is currently unavailable:.
        /// </summary>
        internal static string The_page_is_currently_unavailable_ {
            get {
                return ResourceManager.GetString("The page is currently unavailable:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This data is already being used for another process..
        /// </summary>
        internal static string This_data_is_already_being_used_for_another_process_ {
            get {
                return ResourceManager.GetString("This data is already being used for another process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not completed the input of product data !.
        /// </summary>
        internal static string You_have_not_completed_the_input_of_product_data__ {
            get {
                return ResourceManager.GetString("You have not completed the input of product data !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not completed the payment data input !.
        /// </summary>
        internal static string You_have_not_completed_the_payment_data_input__ {
            get {
                return ResourceManager.GetString("You have not completed the payment data input !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t completed the product data input yet!.
        /// </summary>
        internal static string You_haven_t_completed_the_product_data_input_yet_ {
            get {
                return ResourceManager.GetString("You haven\'t completed the product data input yet!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your trial has expired. Please purchase a license to continue using the application..
        /// </summary>
        internal static string Your_trial_has_expired__Please_purchase_a_license_to_continue_using_the_application_ {
            get {
                return ResourceManager.GetString("Your trial has expired. Please purchase a license to continue using the applicati" +
                        "on.", resourceCulture);
            }
        }
    }
}
